language: python
python:
  - "2.7"
install:
  - npm -g i jshint
  - pip install flake8
  - npm install --prefix prototype/static/prototype
script:
  - flake8 .
  - jshint prototype/static/prototype/src/*.js
