version: "3"
services:
    postgres:
      image: postgres:9.4
      volumes:
          - /data/fsm-designer-svg/postgres:/var/lib/postgresql/data
      env_file: .env

    django:
      build: .
      user: django
      links:
        - postgres
      command: /gunicorn.sh
      env_file: .env
      volumes:
          - static-files:/app/staticfiles

    nginx:
      build: ./compose/nginx
      links:
        - django
      ports:
        - "0.0.0.0:80:80"
      volumes:
          - static-files:/app/staticfiles
volumes:
    static-files:
